const TOGGLE_FORM = "TOGGLE_FORM"
const ADD_WORD = "ADD_WORD"
const SET_FILTER_MODE = "SET_FILTER_MODE"
const TOGGLE_WORD = "TOGGLE_WORD"
const REMOVE_WORD = "REMOVE_WORD"
const FETCH_All_WORDS = "FETCH_All_WORDS"

export default {TOGGLE_FORM,ADD_WORD,SET_FILTER_MODE,TOGGLE_WORD,REMOVE_WORD,FETCH_All_WORDS}

